/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_juneday_FromCWithLove */

#ifndef _Included_se_juneday_FromCWithLove
#define _Included_se_juneday_FromCWithLove
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_juneday_FromCWithLove
 * Method:    getSome
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_se_juneday_FromCWithLove_getSome
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
