#!/bin/sh

CYGWIN=$(uname | grep CYG | wc -l)

dosendsig() {

    if [ "$CYGWIN" != "1" ]
    then
        PID=$(ps auxww| grep "/signal-ex" | grep -v grep | awk '{ printf $2}');
        echo kill "-$1" "$PID" | bash
    else
        
        PID=$(ps auxww| grep "/signal-ex" | grep -v grep | awk '{ printf $1}');
        /usr/bin/kill "-$1" "$PID"
    fi

}



dosendsig $1

